matrix:
  VERSION:
    - "2.22"

build:
  image: armhfbuild/glibc-builder
  environment:
    - STDOUT=1
  commands:
    - cd / && /builder $$VERSION /usr/glibc-compat >/drone/src/glibc-bin-$$VERSION-armhf.tar.gz

publish:
  github_release:
    api_key: $$GITHUB_API_KEY
    files:
      - glibc-bin-$$VERSION-armhf.tar.gz
    checksum: sha1

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
